version: '3.7'

services:
  blogfront:
    build: ./../osa_5_fs2020
    ports:
      - 3000:3000
  backend:
    build: . 
    command: npm start
    ports: 
      - 3001:3001
    volumes:
      - ./:/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: backend

volumes: # This is required for the node_modules named volume
  node_modules: