POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGkiLCJpZCI6IjVmMDM3NDJhNjExZGI5NDAyMGMxZmIwZiIsImlhdCI6MTU5NDA2MTg4M30.QS1YyL-Ri82PA4ndZCMwfUZCZJZTf6cpzhYmLcHomQQ

{
    "title": "sisustuskirja",
    "author": "heli V",
    "url": "helinsome.fi",
    "likes": 1000000 
}